[window]

opacity = 0.9
blur = false

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[font]

normal.family = "DejaVu Sans Mono for Powerline"
bold.family = "DejaVu Sans Mono for Powerline"
italic.family = "DejaVu Sans Mono for Powerline"
bold_italic.family = "DejaVu Sans Mono for Powerline"

size = 11.0

[colors]
primary.foreground = "#2cc55d"

[terminal]
shell.program = "/bin/zsh"
shell.args = [
    "-l",
    "-c",
    "tmux attach -t alacritty || tmux new -s alacritty"
    ]

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[scrolling]
history = 100000
