k9s:
  cluster: gke_bolcom-pro_europe-west4_bolcom-pro-2mq
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - r2d2
      - default
  view:
    active: namespace
  featureGates:
    nodeShell: false
  proxy: null
