k9s:
  cluster: minikube
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - all
      - default
      - metacontroller
  view:
    active: ctx
  featureGates:
    nodeShell: false
  proxy: null
