k9s:
  cluster: gke_bolcom-pro_europe-west4_pro-ew4-006
  namespace:
    active: r2d2
    lockFavorites: false
    favorites:
      - all
      - r2d2
      - default
  view:
    active: ctx
  featureGates:
    nodeShell: false
  proxy: null
